version: "3.8"

services:
  app:
    build: ../docker
    environment:
      - DB_DSN=postgres://${DB_USER:-db_user}:${DB_PASSWORD:-123qwe}@db:5432/${DB_NAME:-docwikify}?sslmode=disable
    networks:
      - docwikify-network
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13-alpine
    container_name: wikidocify-db
    environment:
      - POSTGRES_USER=${DB_USER:-db_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-123qwe}
      - POSTGRES_DB=${DB_NAME:-docwikify}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - docwikify-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  docwikify-network:
    driver: bridge

volumes:
  postgres_data:
