apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "backend.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
stringData:
  POSTGRES_USER: {{ .Values.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
  POSTGRES_DB: {{ .Values.postgres.db }}
